# Generated by Django 4.2.7 on 2023-11-24 05:57

import conferences.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleEn', models.CharField(max_length=255)),
                ('titleJa', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SessionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255)),
                ('title_ja', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('tag_line', models.CharField(blank=True, max_length=255)),
                ('profile_pic_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('logo_url', models.URLField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('plan', models.CharField(choices=[('PLATINUM', 'Platinum'), ('GOLD', 'Gold'), ('SUPPORTER', 'Supporter')], default='SUPPORTER', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='ConferenceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255)),
                ('title_ja', models.CharField(blank=True, max_length=255)),
                ('description_en', models.TextField(blank=True)),
                ('description_ja', models.TextField(blank=True)),
                ('target_audience', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('slide_url', models.URLField(blank=True)),
                ('message_en', models.TextField(blank=True)),
                ('message_ja', models.TextField(blank=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True, validators=[conferences.models.validate_max_duration, conferences.models.validate_min_duration])),
                ('language', models.CharField(choices=[('ENGLISH', 'English'), ('JAPANESE', 'Japanese')], default='ENGLISH', max_length=8)),
                ('session_type', models.CharField(choices=[('WELCOME_TALK', 'Welcome Talk'), ('NORMAL', 'Normal'), ('LUNCH', 'Lunch')], default='NORMAL', max_length=12)),
                ('is_service_session', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conference_sessions', to='conferences.sessioncategory')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conference_sessions', to='conferences.room')),
                ('speakers', models.ManyToManyField(related_name='conference_sessions', to='conferences.speaker')),
            ],
        ),
    ]
