# Generated by Django 4.2.7 on 2023-11-24 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0002_alter_sessioncategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencesession',
            name='interpretation_target',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='conferencesession',
            name='room',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='conference_sessions', to='conferences.room'),
        ),
        migrations.AlterField(
            model_name='conferencesession',
            name='speakers',
            field=models.ManyToManyField(blank=True, related_name='conference_sessions', to='conferences.speaker'),
        ),
    ]
