# Generated by Django 4.2.7 on 2023-11-24 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0003_conferencesession_interpretation_target_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='titleEn',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='titleJa',
            new_name='title_ja',
        ),
    ]
