# Generated by Django 4.2.7 on 2023-11-26 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0004_rename_titleen_room_title_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencesession',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conference_sessions', to='conferences.room'),
        ),
    ]
